review:
  enabled: true
  auto_review_on_open: true
  auto_review_on_update: true
  summarize_comments: true
  comment_tone: friendly
  max_comments: 15
  language: zh-CN  # 👈 新增这一行
  prompt: >
    请使用简体中文生成所有代码审查评论和总结，
    保持语气专业、礼貌且简洁。

  rules:
    - title: "代码风格"
      description: "检查代码风格一致性和 lint 规范。"
      enabled: true
    - title: "安全"
      description: "识别潜在的安全漏洞。"
      enabled: true
    - title: "性能"
      description: "标记可能的性能问题。"
      enabled: true
