<script lang="ts">
  import { apiKeyStore } from "$lib/stores/api";
  import { buildPersonalWebsitePrompt } from "@prompt-hub/prompt";
  import { useAIStream } from "$lib/hooks/useAIStream";

  // 表单数据
  let formData = {
    name: "",
    profession: "",
    skills: "",
    background: "",
    contactType: "email" as "email" | "wechat" | "github",
    contactValue: ""
  };
  
  let githubToken = "";
  let gistUrl = "";
  let isDeploying = false;
  let viewMode: "preview" | "code" = "preview"; // 视图模式：预览或代码

  $: aiStream = useAIStream("personal-website");
  $: state = aiStream.state;
  $: ({ progress, status, result, error } = $state);
  $: statusTip = aiStream.statusTip;
  $: loading = status !== "done" && status !== "error" && status !== "idle";
  
  // 提取HTML代码（去除可能的markdown代码块标记）
  $: htmlCode = result ? extractHtmlCode(result) : "";
  $: hasResult = htmlCode.length > 0;

  // 提取HTML代码的辅助函数
  function extractHtmlCode(text: string): string {
    // 移除markdown代码块标记
    const codeBlockRegex = /```html\s*([\s\S]*?)\s*```/;
    const match = text.match(codeBlockRegex);
    if (match) {
      return match[1].trim();
    }
    
    // 如果没有代码块标记，检查是否直接是HTML
    if (text.includes("<!DOCTYPE") || text.includes("<html")) {
      return text.trim();
    }
    
    return text;
  }

  // 构建自我介绍文本
  function buildIntroduction(): string {
    let intro = "";

    // 基本信息
    if (formData.name || formData.profession) {
      intro += `## 基本信息\n`;
      if (formData.name) intro += `姓名：${formData.name}\n`;
      if (formData.profession) intro += `职业：${formData.profession}\n`;
      intro += `\n`;
    }

    // 技能和爱好
    if (formData.skills.trim()) {
      intro += `## 技能和爱好\n${formData.skills}\n\n`;
    }

    // 背景经历
    if (formData.background.trim()) {
      intro += `## 教育背景/工作经历\n${formData.background}\n\n`;
    }

    // 联系方式
    const contacts = [];
    if (formData.contactValue) {
      const typeMap = {
        email: "邮箱",
        wechat: "微信",
        github: "GitHub"
      };
      contacts.push(`${typeMap[formData.contactType]}：${formData.contactValue}`);
    }
    
    if (contacts.length > 0) {
      intro += `## 联系方式\n${contacts.join("\n")}\n`;
    }

    return intro;
  }

  // 生成个人网站
  async function generateWebsite() {
    if (!$apiKeyStore) return;
    
    // 验证必填项
    if (!formData.name.trim() || !formData.profession.trim()) {
      alert("请至少填写姓名和职业");
      return;
    }

    const introduction = buildIntroduction();
    const prompt = buildPersonalWebsitePrompt() + "\n\n" + introduction;
    await aiStream.invoke(prompt);
  }

  // 下载HTML文件
  function downloadHTML() {
    if (!htmlCode) return;

    const blob = new Blob([htmlCode], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "personal-website.html";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // 部署到GitHub Gist
  async function deployToGist() {
    if (!htmlCode || !githubToken.trim()) {
      alert("请先生成网站并配置 GitHub Token");
      return;
    }

    isDeploying = true;
    gistUrl = "";

    const gistData = {
      description: "Personal Website - Generated by Prompt Hub",
      public: true,
      files: {
        "index.html": {
          content: htmlCode,
        },
      },
    };

    const response = await fetch("https://api.github.com/gists", {
      method: "POST",
      headers: {
        Authorization: `token ${githubToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(gistData),
    });

    if (response.ok) {
      const data = await response.json();
      // 使用 htmlpreview.github.io 来预览 Gist 中的 HTML
      const rawUrl = data.files["index.html"].raw_url;
      gistUrl = `https://htmlpreview.github.io/?${rawUrl}`;
      alert("部署成功！已生成可访问链接");
    } else {
      const errorData = await response.json();
      alert(`部署失败：${errorData.message || "未知错误"}`);
    }

    isDeploying = false;
  }

  // 重置
  function resetAll() {
    formData = {
      name: "",
      profession: "",
      skills: "",
      background: "",
      contactType: "email",
      contactValue: ""
    };
    githubToken = "";
    gistUrl = "";
    aiStream.reset();
  }

  // 全屏显示
  let previewContainer: HTMLElement;
  let isFullscreen = false;
  
  function toggleFullscreen() {
    if (!previewContainer) return;
    
    if (!document.fullscreenElement) {
      previewContainer.requestFullscreen();
    } else {
      document.exitFullscreen();
    }
  }

  // 监听全屏状态变化
  if (typeof window !== 'undefined') {
    document.addEventListener('fullscreenchange', () => {
      isFullscreen = !!document.fullscreenElement;
    });
  }

  // 在新窗口打开
  function openInNewWindow() {
    if (!htmlCode) return;
    
    const blob = new Blob([htmlCode], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    window.open(url, "_blank", "width=1200,height=800");
    
    // 延迟释放 URL，确保新窗口已加载
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
</script>

<svelte:head>
  <title>个人网站生成器 - Prompt Hub</title>
  <meta name="description" content="填写表单信息，AI 生成专业的多页面个人网站，支持实时查看代码和预览" />
</svelte:head>

<div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
  <!-- 页面头部 -->
  <div class="mb-8">
    <div class="flex items-center space-x-4 mb-6">
      <div
        class="w-12 h-12 bg-gradient-to-br from-cyan-500 to-blue-600 rounded-xl flex items-center justify-center shadow-medium"
      >
        <span class="text-white text-xl">🌐</span>
      </div>
      <div>
        <h1 class="text-3xl font-bold text-neutral-800">个人网站生成器</h1>
        <p class="text-neutral-600">填写表单信息，AI 生成专业的多页面个人网站（含路由系统）</p>
      </div>
    </div>
  </div>

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
    <!-- 左侧：输入区域 -->
    <div class="space-y-6">
      <!-- 基本信息 -->
      <div
        class="bg-white/70 backdrop-blur-sm rounded-2xl p-6 shadow-soft border border-white/20"
      >
        <h3
          class="text-lg font-semibold text-neutral-800 mb-4 flex items-center"
        >
          <span class="w-2 h-2 bg-red-500 rounded-full mr-3"></span>
          基本信息 <span class="text-red-500 ml-1">*</span>
        </h3>
        <div class="grid grid-cols-2 gap-4">
          <div>
            <label for="name" class="block text-sm font-medium text-neutral-700 mb-2">
              姓名 <span class="text-red-500">*</span>
            </label>
            <input
              id="name"
              type="text"
              bind:value={formData.name}
              class="w-full px-4 py-2 border border-neutral-300 rounded-lg text-sm focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-colors"
              placeholder="例如：张三"
            />
          </div>
          <div>
            <label for="profession" class="block text-sm font-medium text-neutral-700 mb-2">
              职业 <span class="text-red-500">*</span>
            </label>
            <input
              id="profession"
              type="text"
              bind:value={formData.profession}
              class="w-full px-4 py-2 border border-neutral-300 rounded-lg text-sm focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-colors"
              placeholder="例如：全栈开发工程师"
            />
          </div>
        </div>
      </div>

      <!-- 技能和爱好 -->
      <div
        class="bg-white/70 backdrop-blur-sm rounded-2xl p-6 shadow-soft border border-white/20"
      >
        <h3
          class="text-lg font-semibold text-neutral-800 mb-4 flex items-center"
        >
          <span class="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>
          技能和爱好
        </h3>
        <input
          type="text"
          bind:value={formData.skills}
          class="w-full px-4 py-2 border border-neutral-300 rounded-lg text-sm focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-colors"
          placeholder="例如：前端开发、UI设计、摄影、阅读"
        />
      </div>

      <!-- 背景经历 -->
      <div
        class="bg-white/70 backdrop-blur-sm rounded-2xl p-6 shadow-soft border border-white/20"
      >
        <h3
          class="text-lg font-semibold text-neutral-800 mb-4 flex items-center"
        >
          <span class="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>
          教育背景/工作经历
        </h3>
        <textarea
          bind:value={formData.background}
          class="w-full h-32 p-4 border border-neutral-300 rounded-lg text-sm resize-none focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-colors"
          placeholder="请输入你的教育背景或工作经历，例如：&#10;&#10;• 2018-2022 某某大学 计算机科学与技术&#10;• 2022-至今 某某公司 高级前端工程师&#10;• 负责公司核心产品的前端架构设计..."
        ></textarea>
      </div>

      <!-- 联系方式 -->
      <div
        class="bg-white/70 backdrop-blur-sm rounded-2xl p-6 shadow-soft border border-white/20"
      >
        <h3
          class="text-lg font-semibold text-neutral-800 mb-4 flex items-center"
        >
          <span class="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>
          联系方式 <span class="text-neutral-500 text-sm font-normal ml-2">(可选)</span>
        </h3>
        <div class="flex gap-3">
          <select
            bind:value={formData.contactType}
            class="px-4 py-2 border border-neutral-300 rounded-lg text-sm focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-colors bg-white"
          >
            <option value="email">📧 邮箱</option>
            <option value="wechat">💬 微信</option>
            <option value="github">🐙 GitHub</option>
          </select>
          <input
            type="text"
            bind:value={formData.contactValue}
            class="flex-1 px-4 py-2 border border-neutral-300 rounded-lg text-sm focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-colors"
            placeholder={formData.contactType === "email" ? "your@email.com" : formData.contactType === "wechat" ? "your-wechat-id" : "github.com/username"}
          />
        </div>
      </div>

      <!-- 生成按钮 -->
      <div
        class="bg-white/70 backdrop-blur-sm rounded-2xl p-6 shadow-soft border border-white/20"
      >
        <div class="flex space-x-4">
          <button
            class="flex-1 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-600 hover:to-blue-700 disabled:from-neutral-300 disabled:to-neutral-400 text-white font-medium py-4 px-6 rounded-xl shadow-medium hover:shadow-strong disabled:shadow-none transition-all duration-200 hover:-translate-y-0.5 disabled:translate-y-0 disabled:cursor-not-allowed relative overflow-hidden"
            on:click={generateWebsite}
            disabled={!$apiKeyStore || loading}
          >
            {#if loading && progress > 0}
              <div
                class="absolute inset-0 bg-cyan-400/30 transition-all duration-300 ease-out"
                style="width: {progress}%"
              ></div>
            {/if}
            <span
              class="flex items-center justify-center space-x-2 relative z-10"
            >
              {#if loading}
                <svg
                  class="animate-spin h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    class="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    stroke-width="4"
                  ></circle>
                  <path
                    class="opacity-75"
                    fill="currentColor"
                    d="m4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 714 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                <span>{$statusTip} {progress}%</span>
              {:else}
                <span>🌐</span>
                <span>生成个人网站</span>
              {/if}
            </span>
          </button>

          <button
            on:click={resetAll}
            class="px-6 py-4 bg-neutral-100 hover:bg-neutral-200 text-neutral-700 font-medium rounded-xl transition-colors duration-200"
          >
            重置
          </button>
        </div>
      </div>

      <!-- 部署选项 -->
      {#if hasResult}
        <div
          class="bg-white/70 backdrop-blur-sm rounded-2xl p-6 shadow-soft border border-white/20"
        >
          <h3
            class="text-lg font-semibold text-neutral-800 mb-4 flex items-center"
          >
            <span class="w-2 h-2 bg-green-500 rounded-full mr-3"></span>
            部署选项
          </h3>

          <!-- 下载 HTML -->
          <div class="mb-4">
            <button
              on:click={downloadHTML}
              class="w-full bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white font-medium py-3 px-6 rounded-xl shadow-medium hover:shadow-strong transition-all duration-200 hover:-translate-y-0.5"
            >
              <span class="flex items-center justify-center space-x-2">
                <span>⬇️</span>
                <span>下载 HTML 文件</span>
              </span>
            </button>
            <p class="text-xs text-neutral-500 mt-2 text-center">
              下载后可以自己托管到任何静态网站服务
            </p>
          </div>

          <!-- GitHub Gist 部署 -->
          <div class="pt-4 border-t border-neutral-200">
            <label for="github-token" class="block text-sm font-medium text-neutral-700 mb-2">
              GitHub Token（用于 Gist 托管）
            </label>
            <input
              id="github-token"
              type="password"
              bind:value={githubToken}
              class="w-full px-4 py-2 border border-neutral-300 rounded-lg text-sm focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition-colors mb-3"
              placeholder="ghp_xxxxxxxxxxxxxxxx"
            />
            <button
              on:click={deployToGist}
              disabled={!githubToken.trim() || isDeploying}
              class="w-full bg-gradient-to-r from-purple-500 to-pink-600 hover:from-purple-600 hover:to-pink-700 disabled:from-neutral-300 disabled:to-neutral-400 text-white font-medium py-3 px-6 rounded-xl shadow-medium hover:shadow-strong disabled:shadow-none transition-all duration-200 hover:-translate-y-0.5 disabled:translate-y-0 disabled:cursor-not-allowed"
            >
              <span class="flex items-center justify-center space-x-2">
                {#if isDeploying}
                  <svg
                    class="animate-spin h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      class="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      stroke-width="4"
                    ></circle>
                    <path
                      class="opacity-75"
                      fill="currentColor"
                      d="m4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 714 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                  <span>部署中...</span>
                {:else}
                  <span>🚀</span>
                  <span>部署到 GitHub Gist</span>
                {/if}
              </span>
            </button>

            {#if gistUrl}
              <div class="mt-3 p-3 bg-green-50 border border-green-200 rounded-lg">
                <p class="text-sm text-green-800 mb-2 font-medium">
                  ✅ 部署成功！
                </p>
                <a
                  href={gistUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="text-sm text-blue-600 hover:text-blue-800 underline break-all"
                >
                  {gistUrl}
                </a>
              </div>
            {/if}

            <p class="text-xs text-neutral-500 mt-2">
              需要 GitHub Token？
              <a
                href="https://github.com/settings/tokens/new?scopes=gist"
                target="_blank"
                rel="noopener noreferrer"
                class="text-cyan-600 hover:text-cyan-800 underline"
              >
                点击这里创建
              </a>
              （只需勾选 gist 权限）
            </p>
          </div>
        </div>
      {/if}
    </div>

    <!-- 右侧：预览区域 -->
    <div class="space-y-6">
      <div
        class="bg-white/70 backdrop-blur-sm rounded-2xl p-6 shadow-soft border border-white/20 sticky top-6"
      >
        <!-- 标题和切换按钮 -->
        <div class="flex items-center justify-between mb-4">
          <h3
            class="text-lg font-semibold text-neutral-800 flex items-center"
          >
            <span class="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>
            {viewMode === "preview" ? "实时预览" : "代码视图"}
          </h3>
          
          <!-- 视图切换按钮 -->
          {#if hasResult || loading}
            <div class="flex bg-neutral-100 rounded-lg p-1">
              <button
                on:click={() => viewMode = "preview"}
                class="px-3 py-1.5 rounded-md text-sm font-medium transition-colors"
                class:bg-white={viewMode === "preview"}
                class:text-cyan-600={viewMode === "preview"}
                class:shadow-sm={viewMode === "preview"}
                class:text-neutral-600={viewMode !== "preview"}
              >
                👁️ 预览
              </button>
              <button
                on:click={() => viewMode = "code"}
                class="px-3 py-1.5 rounded-md text-sm font-medium transition-colors"
                class:bg-white={viewMode === "code"}
                class:text-cyan-600={viewMode === "code"}
                class:shadow-sm={viewMode === "code"}
                class:text-neutral-600={viewMode !== "code"}
              >
                💻 代码
              </button>
            </div>
          {/if}
        </div>

        {#if error}
          <div
            class="bg-red-50 border border-red-200 rounded-lg p-4 text-sm text-red-800"
          >
            <p class="font-medium mb-2">⚠️ 生成失败</p>
            <p class="whitespace-pre-wrap">{error}</p>
          </div>
        {:else if viewMode === "preview"}
          <!-- 预览视图 -->
          {#if htmlCode || loading}
            <div class="relative" bind:this={previewContainer}>
              {#if htmlCode}
                <iframe
                  title="网站预览"
                  srcdoc={htmlCode}
                  class="w-full h-[600px] border border-neutral-200 rounded-lg bg-white"
                  sandbox="allow-scripts"
                ></iframe>
                <!-- 操作按钮组 -->
                <div class="absolute top-2 right-2 flex gap-2">
                  <button
                    on:click={openInNewWindow}
                    class="bg-blue-500 hover:bg-blue-600 text-white text-xs px-3 py-1.5 rounded shadow-md transition-colors flex items-center gap-1"
                    title="在新窗口打开"
                  >
                    🔗 新窗口
                  </button>
                  <button
                    on:click={toggleFullscreen}
                    class="hidden md:flex bg-green-500 hover:bg-green-600 text-white text-xs px-3 py-1.5 rounded shadow-md transition-colors items-center gap-1"
                    title={isFullscreen ? "退出全屏" : "全屏显示"}
                  >
                    {#if isFullscreen}
                      ⛶ 退出
                    {:else}
                      ⛶ 全屏
                    {/if}
                  </button>
                </div>
              {:else if loading}
                <div class="flex flex-col items-center justify-center h-[600px] border border-neutral-200 rounded-lg bg-neutral-50">
                  <svg
                    class="animate-spin h-10 w-10 mb-4 text-cyan-500"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      class="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      stroke-width="4"
                    ></circle>
                    <path
                      class="opacity-75"
                      fill="currentColor"
                      d="m4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 714 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                  <p class="text-neutral-500">正在生成你的个人网站...</p>
                  <p class="text-xs text-neutral-400 mt-2">可以切换到"代码视图"查看生成过程</p>
                </div>
              {/if}
            </div>
          {:else}
            <div class="flex flex-col items-center justify-center h-[600px] text-neutral-400">
              <svg
                class="w-16 h-16 mb-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                />
              </svg>
              <p>输入自我介绍后，这里将显示生成的网站预览</p>
            </div>
          {/if}
        {:else}
          <!-- 代码视图 -->
          <div class="relative">
            <pre
              class="w-full h-[600px] overflow-auto bg-neutral-900 text-neutral-100 p-4 rounded-lg text-xs font-mono border border-neutral-700"
            ><code>{result || loading ? (result || "正在生成代码...") : "等待生成..."}</code></pre>
            {#if result}
              <button
                on:click={() => {
                  navigator.clipboard.writeText(result);
                  alert("代码已复制到剪贴板！");
                }}
                class="absolute top-2 right-2 bg-cyan-500 hover:bg-cyan-600 text-white text-xs px-3 py-1.5 rounded transition-colors"
              >
                📋 复制代码
              </button>
            {/if}
          </div>
        {/if}
      </div>
    </div>
  </div>
</div>

<style>
  /* 全屏时的样式 */
  :global(.relative:fullscreen) {
    background: white;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 0;
  }

  :global(.relative:fullscreen iframe) {
    width: 100vw !important;
    height: 100vh !important;
    border: none !important;
    border-radius: 0 !important;
  }

  :global(.relative:fullscreen .absolute) {
    position: fixed !important;
    top: 1rem !important;
    right: 1rem !important;
    z-index: 9999 !important;
  }
</style>

